liip_imagine:
    resolvers:
        default:
        web_path: ~
    filter_sets:
        #cache: default
        project_thumb:
            quality: 75
            filters:
                thumbnail: { size: [36, 36], mode: outbound }